name: example
description: field_key_generator example
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.2.6

dependencies:
  field_key_generator:
    path: ../

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  build_runner: 2.4.9
  
  
